export enum PermissaoUsuarioEnum {

  CADASTRO_MANTEREXEMPLO = 'CADASTRO_MANTEREXEMPLO',
  CADASTRO_PESQUISAREXEMPLO = 'CADASTRO_PESQUISAREXEMPLO',

  CADASTROS_EMPRESA_CONSULTAR = 'CADASTROS_EMPRESA_CONSULTAR',
  CADASTROS_EMPRESA_CADASTRAR = 'CADASTROS_EMPRESA_CADASTRAR',
  CADASTROS_EMPRESA_EDITAR = 'CADASTROS_EMPRESA_EDITAR',
  CADASTROS_EMPRESA_EXCLUIR = 'CADASTROS_EMPRESA_EXCLUIR',
  CADASTROS_EMPRESA_EXPORTARDADOS = 'CADASTROS_EMPRESA_EXPORTARDADOS',

  CADASTROS_SISTEMAEMPRESA_CONSULTAR = 'CADASTROS_SISTEMAEMPRESA_CONSULTAR',
  CADASTROS_SISTEMAEMPRESA_CADASTRAR = 'CADASTROS_SISTEMAEMPRESA_CADASTRAR',
  CADASTROS_SISTEMAEMPRESA_EDITAR = 'CADASTROS_SISTEMAEMPRESA_EDITAR',
  CADASTROS_SISTEMAEMPRESA_EXCLUIR = 'CADASTROS_SISTEMAEMPRESA_EXCLUIR',
  CADASTROS_SISTEMAEMPRESA_EXPORTARDADOS = 'CADASTROS_SISTEMAEMPRESA_EXPORTARDADOS',

  CADASTROS_CONTATOEMPRESA_CONSULTAR = 'CADASTROS_CONTATOEMPRESA_CONSULTAR',
  CADASTROS_CONTATOEMPRESA_CADASTRAR = 'CADASTROS_CONTATOEMPRESA_CADASTRAR',
  CADASTROS_CONTATOEMPRESA_EDITAR= 'CADASTROS_CONTATOEMPRESA_EDITAR',
  CADASTROS_CONTATOEMPRESA_EXCLUIR = 'CADASTROS_CONTATOEMPRESA_EXCLUIR',
  CADASTROS_CONTATOEMPRESA_EXPORTARDADOS = 'CADASTROS_CONTATOEMPRESA_EXPORTARDADOS',

  CADASTROS_TIPODEPARA_CONSULTAR = 'CADASTROS_TIPODEPARA_CONSULTAR',
  CADASTROS_TIPODEPARA_CADASTRAR = 'CADASTROS_TIPODEPARA_CADASTRAR',
  CADASTROS_TIPODEPARA_EDITAR = 'CADASTROS_TIPODEPARA_EDITAR',
  CADASTROS_TIPODEPARA_EXCLUIR = 'CADASTROS_TIPODEPARA_EXCLUIR',
  CADASTROS_TIPODEPARA_EXPORTARDADOS = 'CADASTROS_TIPODEPARA_EXPORTARDADOS',

  CADASTROS_DEPARA_CONSULTAR = 'CADASTROS_DEPARA_CONSULTAR',
  CADASTROS_DEPARA_CADASTRAR = 'CADASTROS_DEPARA_CADASTRAR',
  CADASTROS_DEPARA_EDITAR = 'CADASTROS_DEPARA_EDITAR',
  CADASTROS_DEPARA_EXCLUIR = 'CADASTROS_DEPARA_EXCLUIR',
  CADASTROS_DEPARA_EXPORTARDADOS = 'CADASTROS_DEPARA_EXPORTARDADOS',

  CADASTROS_ASSOC_CONT_NOTIF_SERV_CONSULTAR = 'CADASTROS_ASSOC_CONT_NOTIF_SERV_CONSULTAR',
  CADASTROS_ASSOC_CONT_NOTIF_SERV_CADASTRAR = 'CADASTROS_ASSOC_CONT_NOTIF_SERV_CADASTRAR',
  CADASTROS_ASSOC_CONT_NOTIF_SERV_EDITAR = 'CADASTROS_ASSOC_CONT_NOTIF_SERV_EDITAR',
  CADASTROS_ASSOC_CONT_NOTIF_SERV_EXCLUIR = 'CADASTROS_ASSOC_CONT_NOTIF_SERV_EXCLUIR',
  CADASTROS_ASSOC_CONT_NOTIF_SERV_EXPORTAR = 'CADASTROS_ASSOC_CONT_NOTIF_SERV_EXPORTAR',

  CADASTROS_ACESSO_USUARIO_CONSULTAR = 'CADASTROS_ACESSO_USUARIO_CONSULTAR'
}
