version: "3.1"
services:
  frontend:
    image: nexus-imagens.pbh.gov.br/prodabel/hubsmsa-frontend-hml:latest
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.17.0.54:12201"
        tag: hubsmsa-frontend-hml
    networks:
      - traefik_net
    ports:
      - 80/tcp
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == worker
      update_config:
        delay: 2s
      labels:
      - traefik.docker.network=traefik_net
      - traefik.port=80
      - traefik.frontend.rule=Host:hubsmsa-hm.pbh.gov.br
      - traefik.backend.loadbalancer.stickiness=true
      resources:
        limits:
          cpus: "0.10"
          memory: 128M
        reservations:
          cpus: "0.10"
          memory: 128M
networks:
  traefik_net:
    external:
      name: traefik_net